project:
  type: website
  execute-dir: project
  render: # Add HERE new chapters and new notebooks
    - index.qmd
    - chapters/Exploanatory_Data_Analysis.qmd
    - chapters/Feature_Engeneering.qmd
    - notebooks/notebook1.qmd
    - notebooks/notebook2.qmd

website:
  page-navigation: true
  title: "Template for training resources in Python"
  # In the two URLs below:
  # - replace AIML4OS by the Github account/organization your repository is hosted by;
  # - replace AIML4OS-template-quarto-python by the name of your repository.
  # If your repo is on the AIML4OS organization, change only the name of the repo.
  site-url: "https://AIML4OS.github.io/AIML4OS-template-quarto-python"
  repo-url: "https://github.com/AIML4OS/AIML4OS-template-quarto-python"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents: # Add HERE new chapters (but not the notebooks)
      - href: index.qmd
        text: Introduction
      - href: chapters/Exploanatory_Data_Analysis.qmd
        text: Exploanatory Data Analysis
      - href: chapters/Feature_Engeneering.qmd
        text: Feature Engeneering

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  ipynb:
    output: true


filters:
  - export-metadata.lua

